name: Build Docker image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and tag image
        COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        run: docker build -t ${{ steveacab/freescout-container }}:$COMMIT_SHA -f https://raw.githubusercontent.com/steveacab/freescout-container/refs/heads/main/portainer-stack .
